AWSTemplateFormatVersion: 2010-09-09
Description: Our first template in CloudFormation course.
Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web servers
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: Web server security group
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - Ref: WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-web-server' # StackName-web-server
        - Key: Name2
          Value: !Sub
            - '${AWS::StackName}-web-server-${instanceType}-${str}-${num}'
            - instanceType: !Ref InstanceType
              str: hello
              num: 123
        - Key: Name3
          Value: !Sub
            - 'web-server-${str}-${str}-${num}-${!num}'
            - str: hello
              num: 123
        - Key: Project
          Value: CloudFormation Step By Step
  SQSQueue:
    Type: AWS::SQS::Queue
    DependsOn: WebServerInstance
