AWSTemplateFormatVersion: 2010-09-09
Description: security groups
Parameters:
  SecurityGroupPorts:
    Type: List<Number>
    Description: 'Port numbers as a list: <web-server-port>,<database-port>'
    Default: 80, 3306
  DbSubnets:
    Type: CommaDelimitedList
    Description: 'DB subnet ids as a list: <subnet1>,<subnet2>,...'
    Default: 'subnet-0cc9fb7c1b70c570d, subnet-0ceeb2182a2063f9d, subnet-0acd8489903e7a0fb, subnet-09227140fb95e095d, subnet-0d08f018f7b018712, subnet-061ed6fc8545869bd'
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # Note: Please replace the value of VpcId property with the VPC id of your default VPC
      VpcId: vpc-0f68633eddd78fd56
      GroupDescription: Web server instances security group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort:
            Fn::Select: [0, !Ref SecurityGroupPorts]
          ToPort: !Select [0, !Ref SecurityGroupPorts]
          IpProtocol: tcp
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # Note: Please replace the value of VpcId property with the VPC id of your default VPC
      VpcId: vpc-0f68633eddd78fd56
      GroupDescription: Database instances security group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: !Select [1, !Ref SecurityGroupPorts]
          ToPort: !Select [1, !Ref SecurityGroupPorts]
          IpProtocol: tcp
  DbSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets to launch db instances into
      SubnetIds: !Ref DbSubnets
