AWSTemplateFormatVersion: 2010-09-09
Description: security groups
Parameters:
  SecurityGroupPorts:
    Type: List<Number>
    Description: 'Port numbers as a list: <web-server-port>,<database-port>'
    Default: 80, 3306
  DbSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'DB subnet ids as a list: <subnet1>,<subnet2>,...'
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: A valid VPC id in your AWS account
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Web server instances security group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort:
            Fn::Select: [0, !Ref SecurityGroupPorts]
          ToPort: !Select [0, !Ref SecurityGroupPorts]
          IpProtocol: tcp
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Database instances security group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: !Select [1, !Ref SecurityGroupPorts]
          ToPort: !Select [1, !Ref SecurityGroupPorts]
          IpProtocol: tcp
  DbSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets to launch db instances into
      SubnetIds: !Ref DbSubnets
